# Generated by Django 5.0 on 2024-01-18 00:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commenttopost_commenttopostimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToPostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(choices=[('UPVOTE', 'UPVOTE'), ('DOWNVOTE', 'DOWNVOTE'), ('ANGRY', 'ANGRY'), ('SAD', 'SAD')], max_length=20)),
                ('comment_to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_post_reaction', to='posts.post')),
                ('user_that_react', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
